/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.Fileattributes;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-10-21T14:26:16.817756100+09:00[Asia/Tokyo]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "C-2-2[B] 車両情報連携システム", description = "the C-2-2[B] 車両情報連携システム API")
public interface FileattributesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /fileattributes : C-2-2[B] ファイル属性データモデル取得
     * ファイル属性データモデルのデータを取得します。
     *
     * @param fileName ファイル名。 (optional)
     * @return OK (status code 200)
     *         or リクエスト入力形式不備 (status code 400)
     *         or 認証トークン不備、有効期限切れ、アクセス権限無し (status code 401)
     */
    @Operation(
        operationId = "fileattributesGet",
        summary = "C-2-2[B] ファイル属性データモデル取得",
        description = "ファイル属性データモデルのデータを取得します。",
        tags = { "C-2-2[B] 車両情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/fileattributes",
        produces = { "application/json" }
    )
    
    ResponseEntity<Object> fileattributesGet(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Size(min = 1, max = 4096) @Parameter(name = "fileName", description = "ファイル名。", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fileName", required = false) String fileName
    ); 

}
