/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import java.math.BigDecimal;
import net.ouranos.domain.digiline.model.Resources;
import net.ouranos.domain.digiline.model.Voxel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.UUID;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-02-12T14:32:05.236502600+09:00[Asia/Tokyo]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "C-2-2[B] 車両情報連携システム", description = "the C-2-2[B] 車両情報連携システム API")
public interface ResourcesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /resources : C-2-2[B] 共有資源状態データモデル削除
     * 共有資源状態データモデルのデータを削除します。
     *
     * @param bbox  (optional)
     * @param voxel  (optional)
     * @param mesh  (optional)
     * @param city  (optional)
     * @param roadName 道路名称。道路名称絞り込み対象の場合に指定可能。 (optional)
     * @param category 共有資源カテゴリ名 (optional)
     * @param keyFilter 共有資源名フィルター。正規表現（PCRE）で指定。 (optional)
     * @param lowerBound 共有資源状態値の下限値（包含）。値が整数として解釈できない文字列の場合にのみ有効。 (optional)
     * @param upperBound 共有資源状態値の上限値（排他）。値が整数として解釈できない文字列の場合にのみ有効。 (optional)
     * @return OK (status code 200)
     *         or リクエスト入力形式不備 (status code 400)
     *         or 認証トークン不備、有効期限切れ、アクセス権限無し (status code 401)
     */
    @Operation(
        operationId = "resourcesDelete",
        summary = "C-2-2[B] 共有資源状態データモデル削除",
        description = "共有資源状態データモデルのデータを削除します。",
        tags = { "C-2-2[B] 車両情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/resources"
    )
    
    ResponseEntity<Void> resourcesDelete(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Size(min = 4, max = 4) @Parameter(name = "bbox", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "bbox", required = false) List<@DecimalMin(value = "-180", inclusive = true) @DecimalMax(value = "180", inclusive = true)Double> bbox,
        @Parameter(name = "voxel", description = "", in = ParameterIn.QUERY) @Valid Voxel voxel,
        @DecimalMin("-2147483648") @DecimalMax("2147483647") @Parameter(name = "mesh", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "mesh", required = false) BigDecimal mesh,
        @DecimalMin("-2147483648") @DecimalMax("2147483647") @Parameter(name = "city", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "city", required = false) BigDecimal city,
        @Parameter(name = "roadName", description = "道路名称。道路名称絞り込み対象の場合に指定可能。", in = ParameterIn.QUERY) @Valid @RequestParam(value = "roadName", required = false) String roadName,
        @Parameter(name = "category", description = "共有資源カテゴリ名", in = ParameterIn.QUERY) @Valid @RequestParam(value = "category", required = false) String category,
        @Size(min = 0, max = 4096) @Parameter(name = "keyFilter", description = "共有資源名フィルター。正規表現（PCRE）で指定。", in = ParameterIn.QUERY) @Valid @RequestParam(value = "keyFilter", required = false) String keyFilter,
        @DecimalMin("-2147483648") @DecimalMax("2147483647") @Parameter(name = "lowerBound", description = "共有資源状態値の下限値（包含）。値が整数として解釈できない文字列の場合にのみ有効。", in = ParameterIn.QUERY) @Valid @RequestParam(value = "lowerBound", required = false) BigDecimal lowerBound,
        @DecimalMin("-2147483648") @DecimalMax("2147483647") @Parameter(name = "upperBound", description = "共有資源状態値の上限値（排他）。値が整数として解釈できない文字列の場合にのみ有効。", in = ParameterIn.QUERY) @Valid @RequestParam(value = "upperBound", required = false) BigDecimal upperBound
    ); 


    /**
     * PUT /resources : C-2-2[B] 共有資源状態データモデル設定
     * 共有資源状態データモデルのデータを設定します。指定カテゴリの共有資源状態を設定します。
     *
     * @param resources Request Body (required)
     * @return OK (status code 200)
     *         or リクエスト入力形式不備 (status code 400)
     *         or 認証トークン不備、有効期限切れ、アクセス権限無し (status code 401)
     */
    @Operation(
        operationId = "resourcesPut",
        summary = "C-2-2[B] 共有資源状態データモデル設定",
        description = "共有資源状態データモデルのデータを設定します。指定カテゴリの共有資源状態を設定します。",
        tags = { "C-2-2[B] 車両情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/resources",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Object> resourcesPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "Resources", description = "Request Body", required = true) @Valid @RequestBody Resources resources
    ); 

}
