/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.VehicleIncidentInfo;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-12T09:52:37.728823600+09:00[Asia/Tokyo]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "C-2-2 車両情報連携システム", description = "the C-2-2 車両情報連携システム API")
public interface VehicleIncidentInfoApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /vehicleIncidentInfo
     * 車両インシデント情報登録
     *
     * @param vehicleIncidentInfo 車両インシデント情報 (required)
     * @return OK (status code 200)
     *         or パラメータエラー (status code 400)
     *         or アクセストークン切れによるユーザー認証失敗が発生した場合 (status code 401)
     *         or 登録対象の情報にアクセス権がない場合 (status code 403)
     *         or 外部APIとの通信失敗やデータベースアクセスエラーなどのシステムエラーの場合 (status code 500)
     */
    @Operation(
        operationId = "vehicleIncidentInfoPut",
        description = "車両インシデント情報登録",
        tags = { "C-2-2 車両情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/vehicleIncidentInfo",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> vehicleIncidentInfoPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "VehicleIncidentInfo", description = "車両インシデント情報", required = true) @Valid @RequestBody VehicleIncidentInfo vehicleIncidentInfo
    ); 

}
