/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.TargetInfo;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-01-31T15:02:44.938518700+09:00[Asia/Tokyo]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "環境情報連携システム", description = "the 環境情報連携システム API")
public interface TargetInfoApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /targetInfo
     * &#39;環境情報連携システムから物標情報データモデルのデータを取得します． 時刻の指定がない場合，機器識別IDごとの最新データを返します.&#39;
     *
     * @param serviceLocationID サービス地点ID (required)
     * @param roadsideUnitID 路側機ID (required)
     * @param deviceID 機器識別ID．入力がない場合，全機器の情報を取得． (optional)
     * @param startAt データ取得開始時刻 (optional)
     * @param endAt データ取得開始時刻 (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "targetInfoGet",
        description = "'環境情報連携システムから物標情報データモデルのデータを取得します． 時刻の指定がない場合，機器識別IDごとの最新データを返します.'",
        tags = { "環境情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/targetInfo",
        produces = { "application/json" }
    )
    
    ResponseEntity<Object> targetInfoGet(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @NotNull @Parameter(name = "serviceLocationID", description = "サービス地点ID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "serviceLocationID", required = true) Long serviceLocationID,
        @NotNull @Parameter(name = "roadsideUnitID", description = "路側機ID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "roadsideUnitID", required = true) Long roadsideUnitID,
        @Parameter(name = "deviceID", description = "機器識別ID．入力がない場合，全機器の情報を取得．", in = ParameterIn.QUERY) @Valid @RequestParam(value = "deviceID", required = false) Integer deviceID,
        @Parameter(name = "startAt", description = "データ取得開始時刻", in = ParameterIn.QUERY) @Valid @RequestParam(value = "startAt", required = false) String startAt,
        @Parameter(name = "endAt", description = "データ取得開始時刻", in = ParameterIn.QUERY) @Valid @RequestParam(value = "endAt", required = false) String endAt
    ); 


    /**
     * PUT /targetInfo
     * 環境情報連携システムへ物標情報データモデルのデータを新規作成or更新します。
     *
     * @param targetInfo Request Body (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "targetInfoPut",
        description = "環境情報連携システムへ物標情報データモデルのデータを新規作成or更新します。",
        tags = { "環境情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/targetInfo",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Object> targetInfoPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "TargetInfo", description = "Request Body", required = true) @Valid @RequestBody TargetInfo targetInfo
    ); 

}
