/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.VehicleSchedule;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;
import jakarta.annotation.Generated;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-03T10:04:46.242665100+09:00[Asia/Tokyo]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "vehicles", description = "the vehicles API")
public interface VehicleScheduleApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /vehicle-schedule
     * 自動運転車両のスケジュールを登録します。
     *
     * @param vehicleSchedule Register a schedule. (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "vehicleSchedulePost",
        description = "自動運転車両のスケジュールを登録します。",
        tags = { "vehicles" }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/vehicle-schedule",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> vehicleSchedulePost(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "VehicleSchedule", description = "Register a schedule.", required = true) @Valid @RequestBody VehicleSchedule vehicleSchedule
    ); 

}
