/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import java.math.BigDecimal;
import net.ouranos.domain.digiline.model.ShipperTransCapacity;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-02-07T16:09:48.826789700+09:00[Asia/Tokyo]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "C-4 共同配送システム", description = "the C-4 共同配送システム API")
public interface ShipperTransCapacityApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /shipper_trans_capacity : 運送能力情報を削除
     * 運送能力情報を削除します。
     *
     * @param trspCliPrtyHeadOffId 削除したい運送事業者コード（本社） (required)
     * @param trspCliPrtyBrncOffId 運送事業者コード（事業所） (required)
     * @param serviceNo 便・ダイヤ番号 (required)
     * @param serviceStrtDate 便の運行日 (required)
     * @return 運送能力情報を正常に削除しました。 (status code 201)
     *         or HTTP400エラー (status code 400)
     *         or HTTP500エラー (status code 500)
     */
    @Operation(
        operationId = "shipperTransCapacityDelete",
        summary = "運送能力情報を削除",
        description = "運送能力情報を削除します。",
        tags = { "C-4 共同配送システム" }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/shipper_trans_capacity"
    )
    
    ResponseEntity<Void> shipperTransCapacityDelete(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @NotNull @Parameter(name = "trsp_cli_prty_head_off_id", description = "削除したい運送事業者コード（本社）", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "trsp_cli_prty_head_off_id", required = true) String trspCliPrtyHeadOffId,
        @NotNull @Parameter(name = "trsp_cli_prty_brnc_off_id", description = "運送事業者コード（事業所）", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "trsp_cli_prty_brnc_off_id", required = true) String trspCliPrtyBrncOffId,
        @NotNull @Parameter(name = "service_no", description = "便・ダイヤ番号", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "service_no", required = true) String serviceNo,
        @NotNull @Parameter(name = "service_strt_date", description = "便の運行日", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "service_strt_date", required = true) String serviceStrtDate
    ); 


    /**
     * GET /shipper_trans_capacity : 指定した条件の運送能力情報を取得
     * 指定した条件に基づいて、運送能力情報を取得します。
     *
     * @param serviceNo 便・ダイヤ番号 (optional)
     * @param serviceName 便・ダイヤ名称 (optional)
     * @param carMaxLoadCapacity1Meas 最大積載量1 (optional)
     * @param trspOpStrtAreaLineOneTxt 運行開始地域 (optional)
     * @param trspOpEndAreaLineOneTxt 運行終了地域 (optional)
     * @param maxTrspOpDateTrmStrtDate 運行開始日最大値 (optional)
     * @param minTrspOpDateTrmStrtDate 運行開始日最小値 (optional)
     * @param maxTrspOpDateTrmEndDate 運行終了日最大値 (optional)
     * @param minTrspOpDateTrmEndDate 運行終了日最小値 (optional)
     * @param maxTrspOpPlanDateTrmStrtTime 運行開始希望時刻最大値 (optional)
     * @param minTrspOpPlanDateTrmStrtTime 運行開始希望時刻最小値 (optional)
     * @param maxTrspOpPlanDateTrmEndTime 運行終了希望時刻最大値 (optional)
     * @param minTrspOpPlanDateTrmEndTime 運行終了希望時刻最小値 (optional)
     * @return 指定した条件に基づいて、運送能力情報を正常に取得しました。 (status code 200)
     *         or HTTP400エラー (status code 400)
     *         or HTTP500エラー (status code 500)
     */
    @Operation(
        operationId = "shipperTransCapacityGet",
        summary = "指定した条件の運送能力情報を取得",
        description = "指定した条件に基づいて、運送能力情報を取得します。",
        tags = { "C-4 共同配送システム" }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/shipper_trans_capacity",
        produces = { "application/json" }
    )
    
    ResponseEntity<Object> shipperTransCapacityGet(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "service_no", description = "便・ダイヤ番号", in = ParameterIn.QUERY) @Valid @RequestParam(value = "service_no", required = false) String serviceNo,
        @Parameter(name = "service_name", description = "便・ダイヤ名称", in = ParameterIn.QUERY) @Valid @RequestParam(value = "service_name", required = false) String serviceName,
        @Parameter(name = "car_max_load_capacity1_meas", description = "最大積載量1", in = ParameterIn.QUERY) @Valid @RequestParam(value = "car_max_load_capacity1_meas", required = false) BigDecimal carMaxLoadCapacity1Meas,
        @Parameter(name = "trsp_op_strt_area_line_one_txt", description = "運行開始地域", in = ParameterIn.QUERY) @Valid @RequestParam(value = "trsp_op_strt_area_line_one_txt", required = false) String trspOpStrtAreaLineOneTxt,
        @Parameter(name = "trsp_op_end_area_line_one_txt", description = "運行終了地域", in = ParameterIn.QUERY) @Valid @RequestParam(value = "trsp_op_end_area_line_one_txt", required = false) String trspOpEndAreaLineOneTxt,
        @Parameter(name = "max_trsp_op_date_trm_strt_date", description = "運行開始日最大値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "max_trsp_op_date_trm_strt_date", required = false) String maxTrspOpDateTrmStrtDate,
        @Parameter(name = "min_trsp_op_date_trm_strt_date", description = "運行開始日最小値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "min_trsp_op_date_trm_strt_date", required = false) String minTrspOpDateTrmStrtDate,
        @Parameter(name = "max_trsp_op_date_trm_end_date", description = "運行終了日最大値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "max_trsp_op_date_trm_end_date", required = false) String maxTrspOpDateTrmEndDate,
        @Parameter(name = "min_trsp_op_date_trm_end_date", description = "運行終了日最小値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "min_trsp_op_date_trm_end_date", required = false) String minTrspOpDateTrmEndDate,
        @Parameter(name = "max_trsp_op_plan_date_trm_strt_time", description = "運行開始希望時刻最大値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "max_trsp_op_plan_date_trm_strt_time", required = false) String maxTrspOpPlanDateTrmStrtTime,
        @Parameter(name = "min_trsp_op_plan_date_trm_strt_time", description = "運行開始希望時刻最小値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "min_trsp_op_plan_date_trm_strt_time", required = false) String minTrspOpPlanDateTrmStrtTime,
        @Parameter(name = "max_trsp_op_plan_date_trm_end_time", description = "運行終了希望時刻最大値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "max_trsp_op_plan_date_trm_end_time", required = false) String maxTrspOpPlanDateTrmEndTime,
        @Parameter(name = "min_trsp_op_plan_date_trm_end_time", description = "運行終了希望時刻最小値", in = ParameterIn.QUERY) @Valid @RequestParam(value = "min_trsp_op_plan_date_trm_end_time", required = false) String minTrspOpPlanDateTrmEndTime
    ); 


    /**
     * PUT /shipper_trans_capacity : 運送能力情報を登録
     * 運送能力情報を登録します。
     *
     * @param shipperTransCapacity 運送能力情報 (required)
     * @return 運送能力情報を正常に登録しました。 (status code 201)
     *         or モビリティハブ予約失敗。 (status code 210)
     *         or HTTP400エラー (status code 400)
     *         or HTTP500エラー (status code 500)
     */
    @Operation(
        operationId = "shipperTransCapacityPut",
        summary = "運送能力情報を登録",
        description = "運送能力情報を登録します。",
        tags = { "C-4 共同配送システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/shipper_trans_capacity",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> shipperTransCapacityPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "ShipperTransCapacity", description = "運送能力情報", required = true) @Valid @RequestBody ShipperTransCapacity shipperTransCapacity
    ); 

}
