/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.TrspAbilityLineItem;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-13T16:38:12.592317500+09:00[Asia/Tokyo]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "共同配送システム", description = "the 共同配送システム API")
public interface TrspAbilityLineItemApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /trsp_ability_line_item
     * 運送能力明細を登録します。trsp_ability_line_item
     *
     * @param trspAbilityLineItem 運送事業者、車輌情報、車輌稼働可能リソース (required)
     * @return 登録の正常終了 (status code 200)
     */
    @Operation(
        operationId = "trspAbilityLineItemPut",
        description = "運送能力明細を登録します。trsp_ability_line_item",
        tags = { "共同配送システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/trsp_ability_line_item",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Object> trspAbilityLineItemPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "TrspAbilityLineItem", description = "運送事業者、車輌情報、車輌稼働可能リソース", required = true) @Valid @RequestBody TrspAbilityLineItem trspAbilityLineItem
    ); 

}
