/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.TrackBySip;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Optional;
import java.util.UUID;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-01-08T09:47:12.227334+09:00[Asia/Tokyo]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "C-4 車両情報連携システム", description = "the C-4 車両情報連携システム API")
public interface TrackBySIPApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /trackBySIP : Update or Create TrackBySIP
     * update a new track resource by SIP format. When 200, no response body is returned. | SIP標準メッセージレイアウトの運送依頼請け情報を受取るAPIです。 運送依頼請け情報の必須項目はすべて受け取れるようになっています。REQUEST BODY SCHEMAに記した以外の項目は無視されます。 正常に処理された場合、レスポンスボディは空となります。
     *
     * @param X_TENANT_ID Tenant ID (こちらから提供した固定値を入れていただく予定です。) (required)
     * @param trackBySip  (required)
     * @return Request processed successfully with no response body. (status code 200)
     *         or Bad Request - The server could not understand the request due to invalid syntax. (status code 400)
     *         or Unauthorized - Authentication is required and has failed or has not yet been provided. (status code 401)
     *         or Forbidden - The client does not have access rights to the content. (status code 403)
     *         or Not Found - The server could not find the requested resource. (status code 404)
     *         or Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request. (status code 500)
     */
    @Operation(
        operationId = "trackBySIPPut",
        summary = "Update or Create TrackBySIP",
        description = "update a new track resource by SIP format. When 200, no response body is returned. | SIP標準メッセージレイアウトの運送依頼請け情報を受取るAPIです。 運送依頼請け情報の必須項目はすべて受け取れるようになっています。REQUEST BODY SCHEMAに記した以外の項目は無視されます。 正常に処理された場合、レスポンスボディは空となります。",
        tags = { "C-4 車両情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/trackBySIP",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> trackBySIPPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @NotNull @Parameter(name = "X-TENANT-ID", description = "Tenant ID (こちらから提供した固定値を入れていただく予定です。)", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-TENANT-ID", required = true) String X_TENANT_ID,
        @Parameter(name = "TrackBySip", description = "", required = true) @Valid @RequestBody TrackBySip trackBySip
    ); 

}
