/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.VehicleIncidentInfo;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-01-08T11:24:45.648210400+09:00[Asia/Tokyo]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "C-4 車両情報連携システム", description = "the C-4 車両情報連携システム API")
public interface VehicleIncidentInfoApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /vehicleIncidentInfo : Incident 及び Delay の情報更新
     * Incident 及び Delay の情報更新。このエンドポイントは、200 OK ステータスを返却し、コンテンツは含まれません。
     *
     * @param vehicleIncidentInfo 車両インシデント情報 (required)
     * @return OK (status code 200)
     *         or NG (status code 500)
     */
    @Operation(
        operationId = "vehicleIncidentInfoPut",
        summary = "Incident 及び Delay の情報更新",
        description = "Incident 及び Delay の情報更新。このエンドポイントは、200 OK ステータスを返却し、コンテンツは含まれません。",
        tags = { "C-4 車両情報連携システム" }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/vehicleIncidentInfo",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> vehicleIncidentInfoPut(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "VehicleIncidentInfo", description = "車両インシデント情報", required = true) @Valid @RequestBody VehicleIncidentInfo vehicleIncidentInfo
    ); 

}
